# This file was generated by GoReleaser. DO NOT EDIT.
cask "leaktk" do
  version "0.3.9"

  on_macos do
    on_arm do
      sha256 "d6318b10ab17fa67bb8b578cecc0d1093f90880136eb79e59341ced6da46f1ba"
      url "https://github.com/leaktk/leaktk/releases/download/v#{version}/leaktk-#{version}-darwin-arm64.tar.xz",
        verified: "github.com/leaktk/leaktk"
    end
    on_intel do
      sha256 "7bc20aaba4cc3b7a82662efcb002076ab2fc039078c3e7dea04fb4d0c2560064"
      url "https://github.com/leaktk/leaktk/releases/download/v#{version}/leaktk-#{version}-darwin-x86_64.tar.xz",
        verified: "github.com/leaktk/leaktk"
    end
  end
  on_linux do
    on_arm do
      sha256 "0b4e08fefaec8d49a5b782c550410c40514de5278338fae7c948b91da0cf9783"
      url "https://github.com/leaktk/leaktk/releases/download/v#{version}/leaktk-#{version}-linux-arm64.tar.xz",
        verified: "github.com/leaktk/leaktk"
    end
    on_intel do
      sha256 "9321a76e18daa2a5fef8ebd4083db13894b344a2f805d1a7501a3f96da686872"
      url "https://github.com/leaktk/leaktk/releases/download/v#{version}/leaktk-#{version}-linux-x86_64.tar.xz",
        verified: "github.com/leaktk/leaktk"
    end
  end

  name "leaktk"
  desc "A growing toolkit of utilities for leak detection, mitigation and prevention."
  homepage "https://github.com/leaktk/leaktk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "leaktk"
  bash_completion "completions/bash/leaktk"
  fish_completion "completions/fish/leaktk.fish"
  zsh_completion "completions/zsh/_leaktk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/leaktk"]
    end
  end

  # No zap stanza required
end
