# This file was generated by GoReleaser. DO NOT EDIT.
cask "leaktk" do
  name "leaktk"
  desc "A growing toolkit of utilities for leak detection, mitigation and prevention."
  homepage "https://github.com/leaktk/leaktk"
  version "0.2.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "leaktk"
  bash_completion "completions/bash/leaktk"
  zsh_completion "completions/zsh/_leaktk"
  fish_completion "completions/fish/leaktk.fish"

  on_macos do
    on_intel do
      url "https://github.com/leaktk/leaktk/releases/download/v#{version}/leaktk-#{version}-darwin-x86_64.tar.xz",
        verified: "github.com/leaktk/leaktk"
      sha256 "8002b4b2f6887aa2ea31df724745b6be5c61cfbf816ef451f2de4c2de426becc"
    end
    on_arm do
      url "https://github.com/leaktk/leaktk/releases/download/v#{version}/leaktk-#{version}-darwin-arm64.tar.xz",
        verified: "github.com/leaktk/leaktk"
      sha256 "858e9ab61da5a01ab56918d793970a044ced445e50f9e379933906055635158b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/leaktk/leaktk/releases/download/v#{version}/leaktk-#{version}-linux-x86_64.tar.xz",
        verified: "github.com/leaktk/leaktk"
      sha256 "f459d9c62836c3544c7a5b5429223bd84ae1b91d85a68664999f102963ec48f7"
    end
    on_arm do
      url "https://github.com/leaktk/leaktk/releases/download/v#{version}/leaktk-#{version}-linux-arm64.tar.xz",
        verified: "github.com/leaktk/leaktk"
      sha256 "11e1a751bec88b0e1590a47165cbd4ce109ef5fe2d83b1378df920b102379427"
    end
  end

  # No zap stanza required
end
