# This file was generated by GoReleaser. DO NOT EDIT.
cask "leaktk" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "308ca4ded461fa7e76a4f7147a073796c6a580e09d8a9004a0870ca79755b11a"
      url "https://github.com/leaktk/leaktk/releases/download/v#{version}/leaktk-#{version}-darwin-x86_64.tar.xz",
        verified: "github.com/leaktk/leaktk"
    end
    on_arm do
      sha256 "8aa50ce84a555249fde59cdfa9fda59d63e8a40071fe4b3cf5773c74dd11c0a1"
      url "https://github.com/leaktk/leaktk/releases/download/v#{version}/leaktk-#{version}-darwin-arm64.tar.xz",
        verified: "github.com/leaktk/leaktk"
    end
  end

  on_linux do
    on_intel do
      sha256 "ff5f793658aeeeb9479677e644b6420719d2bbfa21afc306a6aa4d0549779ae5"
      url "https://github.com/leaktk/leaktk/releases/download/v#{version}/leaktk-#{version}-linux-x86_64.tar.xz",
        verified: "github.com/leaktk/leaktk"
    end
    on_arm do
      sha256 "19a94b4bdd0993169b6dfcb566532069ed97a0134f9d2f7090bb92a9e36d7482"
      url "https://github.com/leaktk/leaktk/releases/download/v#{version}/leaktk-#{version}-linux-arm64.tar.xz",
        verified: "github.com/leaktk/leaktk"
    end
  end

  name "leaktk"
  desc "A growing toolkit of utilities for leak detection, mitigation and prevention."
  homepage "https://github.com/leaktk/leaktk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "leaktk"
  bash_completion "completions/bash/leaktk"
  fish_completion "completions/fish/leaktk.fish"
  zsh_completion "completions/zsh/_leaktk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/leaktk"]
    end
  end

  # No zap stanza required

end
